a

diff --git a/MonitorRed/configuracion b/MonitorRed/configuracion
--- a/MonitorRed/configuracion
+++ b/MonitorRed/configuracion
@@ -84,7 +84,18 @@ else
 fi
 }
 
+# Función para validar el puerto
+validate_port() {
+    local port=$1
 
+    if [[ ! $port =~ ^[0-9]+$ ]] || [[ $port -lt 1 ]] || [[ $port -gt 65535 ]]; then
+        port_correcto="si"
+    else
+        echo -e "${amarillo} Error: en el numero de puerto.${borra_colores}"
+        port_correcto="no"
+    fi
+
+}
 
 
 
@@ -118,6 +129,49 @@ do
     echo -e -n "${azul} Selecciona numero de las opciones del menu (Control+c = Salir) ->${borra_colores} "; read opcion
     case $opcion in
         1)  #configurar Servicios
+            # Buscar la cadena "declare -A ips" en el archivo
+            if ! grep -q 'declare -A servicios' "$ruta_ejecucion/MonitorRedServicios.config"; then
+                echo "declare -A servicios" >> $ruta_ejecucion/MonitorRedServicios.config
+            fi
+
+
+            while true
+            do
+                clear
+                echo ""
+                echo -e "${azul}- Listado de tus SERVICIOS para saber si estan avtivos. -${borra_colores}"
+                echo ""
+                tail -n +2 $ruta_ejecucion/MonitorRedServicios.config 2>/dev/null | awk -F'[[\]=]+' '{print "\033[32m" $3 "\033[0m =", "\033[32m" $2 "\033[0m"}' | column -t; echo ""
+                echo ""
+
+                # Solicitar y validar la dirección IP
+                echo -e "${amarillo} Ej. router 192.168.1.1 8080 (S -> Terminar de introducir datos.).${borra_colores}"
+                read -p " Dime un Nombre Dispositivo espacio y su dirección IP espacio su PUERTO -> " name ip port
+                echo ""
+                if  [ "$name" == "s" ] || [ "$name" == "S" ]; then
+                    sed -i 's/configurado_ips="no"/configurado_ips="si"/' $ruta_ejecucion/configuradosino
+                    break
+                fi
+
+                validate_ip "$ip"
+                validate_name "$name"
+                validate_port "$port"
+
+                # Verifica si se debe salir del bucle
+
+
+                # Agrega la entrada al archivo como un nuevo elemento del array
+                if [[ "$ip_correpto" == "si" ]] && [[ "$nombre_correpto" == "si" ]] && [[ "$port_correcto" = "si" ]]; then
+                    echo "servicios[$ip:$port]=$name" >> $ruta_ejecucion/MonitorRedIps.config
+                    echo ""
+                    echo -e " Dispositivo ${azul}$name${borra_colores} con la ${azul}$ip:$port${borra_colores} = ${verde}ok${borra_colores}."
+                    sleep 2
+                else
+                    echo -e "${rojo} Datos de dispositivo incorreptos.${borra_colores}"
+                    echo ""
+                    read -p " Pulsa una tecla para continuar." p
+                fi
+            done
             ;;
 
         2)  #configurar configurado_ips
@@ -131,7 +185,7 @@ do
             do
                 clear
                 echo ""
-                echo -e "${azul}- Listado de tus Ips para su comprobacion. -${borra_colores}"
+                echo -e "${azul}- Listado de tus IPS para saber si estan activas. -${borra_colores}"
                 echo ""
                 tail -n +2 $ruta_ejecucion/MonitorRedIps.config 2>/dev/null | awk -F'[[\]=]+' '{print "\033[32m" $3 "\033[0m =", "\033[32m" $2 "\033[0m"}' | column -t; echo ""
                 echo ""
